version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
    ports:
      - '8000:8000'
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - app
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
